### ISSUE TITLE
link hook returning a Module vs. loader.set()

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#18]
A link hook can return a Module. Suppose something did loader.set() at some point and now there is a module with that name already in the registry. This is an error, right?

**Comment by dherman** [comment]
clobber that sucka

**Comment by jorendorff** [comment]
> This is an error, right?

Wrong, the module returned by the link hook clobbers whatever came before (just like all other cases involving loader.set()). Nothing to implement here, closing.
