### ISSUE TITLE
duplicate mismatching .import calls

### ISSUE THREAD

**Issue by dherman** [jorendorff/js-loaders#2]
What should happen when:

``` js
System.import("x", done, fail, {url: "x1.js"});
System.import("x", done, fail, {url: "x2.js"});
```

(Note the different urls.)

If we see the registry purely as a cache, we should really get two competing loads here, and whichever one finishes later gets an error... hmm. Perhaps a synchronous error on the second `System.import()` call would be better.

**Comment by samth** [comment]
The two different `url` fields don't meaningfully distinguish the two requests.  In the same way that two syntactic `import` declarations from two different modules named `"x1"` and `"x2"` will get turned into one request, these two will become one request, even thought the referring url is different, and thus either both will succeed or both fail.

There is one way that these could be different, which is if the normalize hook for `System` produces _different_ module names for these two, based on the url (or based on `Math.random()`).

**Comment by samth** [comment]
@dherman points out the the rest of the pipeline (after `normalize`) will see the referrer information from the _first_ request (again, assuming that `normalize` produces the same thing for both calls).

**Comment by jorendorff** [comment]
Right, this makes perfect sense to me now.  I wrote that comment before I understood what options.url was actually for. Bogus issue.
