### ISSUE TITLE
Make sure hierarchical module names are sufficient for packages

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#22]
When you `import "foo"`, and "foo" is a package, and the source code is actually in foo/main.js, what happens? `resolve("foo")` can't return "foo/main.js"; it would mess up relative imports in foo/main to import it as foo.

jrburke pointed out that his preferred way is to autogenerate foo:

```
module "foo" {
    export * from "foo/main";
}
```

Module loaders can do this (given enough configuration info). Or the server could do it.

Let's talk about this use case a bit.

**Comment by dherman** [comment]
jrburke's approach is fine and probably the easiest. Another approach is for a build tool to allow either foo.js or foo/main.js and canonicalize (adjusting any relative imports accordingly). Basically I think the state of affairs here is fine.

**Comment by dherman** [comment]
For single-file deployments (which I expect will be common), I think really solving this issue depends on having an expressive enough "ondemand" table (God, that needs a better name) so you can do things like say "jquery/*" maps to a single script file containing multiple modules. That lets one person deploy a multi-module package in a single file and a client include it with a single line of code.

For multi-file deployments, we might also want a way to say in the ondemand table that "jquery/*" maps to a directory hierarchy with "main.js" or "index.js" or some such as the main module. That way you can deploy a package in a self-contained directory hierarchy.

**Comment by samth** [comment]
See Issue #25 for how to make `ondemand` expressive.
