### ISSUE TITLE
System.fetch doesn't seem to be implementable in terms of XHR

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#24]
The fetch hook has to know the "actualAddress" from which it fetched a resource; XHR doesn't seem to expose that. (?!)

**Comment by samth** [comment]
Is this just about XHR not exposing redirect information?

**Comment by jorendorff** [comment]
Yes.

**Comment by jorendorff** [comment]
Talked with @dherman and we're tentatively ok with this. We'll work it out with web standards people, we guess. For now I'm going to implement it using XHR and it'll just not be quite right w.r.t. redirects.
