### ISSUE TITLE
AGREE ON A DESIGN FOR skip/mischiefManaged.

### ISSUE THREAD

**Issue by samth** [jorendorff/js-loaders#3]
P1 ISSUE: AGREE ON A DESIGN FOR skip/mischiefManaged.

The spec calls the third callback argument to the fetch hook
'skip'.

skip() means "i'm not going to fetch this url, you'll never hear
from me again-- but don't worry about it, someone will get the
modules you want and eval() or loader.set() them into existence".
It is a way to support bulk-loading. A fetch hook could respond
to everything with skip()!

But I think I talked samth into changing the hook to have a name
like done() or, jokingly, mischiefManaged(), and require the
fetch hook to call it only _after_ the desired module is
available. The problem with skip() was that it left the loader
with an impression that some work would be done, but no
expectation of an error callback if it went wrong. The error
callback is important; failure must kill the whole LinkageUnit
and call its fail hook. --jorendorff, 2013 April 22.

P1 ISSUE: Want use cases/rationale for skip/mischiefManaged.
--jorendorff, 2013 April 24.

https://github.com/jorendorff/js-loaders/blob/master/loaders.js#L1072

**Comment by samth** [comment]
After conversation with @dherman, we agree on the `done()` design. 

Note that this means that the bulk loading implementation will have to do something like the following.
1. Make one big XHR.
2. In the success callback for the XHR, call exactly one `fulfill()` callback with type "script" and all of the source, followed by a bunch of `done()` calls. 

Note also that there's a maybe-tricky issue with whether we're parsing all the source synchronously before checking if the `done()` calls are allowed.

**Comment by samth** [comment]
Further note: we should talk to Eric F (from the YUI team, who proposed the bulk-loading w/ `skip()` design) to find out if he thinks this works well enough.

**Comment by samth** [comment]
Final note: the rationale for `done()` is to support a bulk-fetch of all the modules requested (in the same turn) by the compilation of some source.

**Comment by jorendorff** [comment]
Oh, I see. The resolve hook is too early (and too synchronous) to dynamically collect exactly the requested URLs.

Still, even without `done()`, a fetch hook could issue an XHR for (say) a tarball, then carve up the response and call each `fulfill()` callback. Static concatenation and ondemand is another option when you're in this kind of situation. SPDY could help. I'm saying there are lots of ways to attack the problem of download speed. Maybe this is a feature we can do without.

If we do need it, we have to answer the question about whether the fulfill() callback parses scripts synchronously in the affirmative, right? Either that or _it_ has to provide a "done fulfilling" callback,  `this.fulfill(src, script, actualUrl, callDoneCallbacks)`... :horse: :banana:

**Comment by samth** [comment]
> Still, even without done(), a fetch hook could issue an XHR for (say) a tarball, then carve up the response and call each fulfill() callback. Static concatenation and ondemand is another option when you're in this kind of situation. SPDY could help. I'm saying there are lots of ways to attack the problem of download speed. Maybe this is a feature we can do without.

Ah, that's an excellent point.  Maybe we can just drop `done()`.  We should talk to Eric.

> If we do need it, we have to answer the question about whether the fulfill() callback parses scripts synchronously in the affirmative, right? 

Right.  The alternative is just too horrible.

**Comment by jorendorff** [comment]
I guess it's still observable whether fulfill() parses scripts synchronously even without done(), so we should probably specify it to be sync... it just wouldn't be as important without done().

**Comment by samth** [comment]
Yes, I agree on both counts.

**Comment by jorendorff** [comment]
Talked to @dherman and he agrees we can drop done().

We'll try to build examples to make sure Eric's use case is adequately covered.
