### ISSUE TITLE
`evalAsync` and `load`: make callback and errback arguments last

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#30]
For `Future` compatibility:

```
loader.evalAsync(src, options, callback, errback)
loader.evalAsync(src, options).then(callback, errback)
```

In the short term, the options end up not being optional, but I think futures are going to go through.

**Comment by dherman** [comment]
I find your reasoning to be valid. I hereby offer up my confirmation of the conclusion. This concludes my feedback.
