### ISSUE TITLE
What options to pass to which hooks

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#34]
Should we pass `type` to the `fetch` hook? What about `extra`?

We should probably pass everything we've got to every hook ...and maybe even change how this stuff works a little bit so we don't have to create so many objects.

**Comment by samth** [comment]
On Thu, May 30, 2013 at 11:25 AM, Jason Orendorff
notifications@github.com wrote:

> We should probably pass everything we've got to every hook

Yes.

> and maybe even change how this stuff works a little bit so we don't have to create so many objects.

Are we really worried about this much allocation?

Sam

**Comment by jorendorff** [comment]
I'm more worried that it's not a very idiomatic API. Objects that look similar turn out not to be the same object. It's confusing.

It's not awful, but maybe we can do better.

**Comment by samth** [comment]
As in, you'd expect mutating one to change the later ones?

**Comment by samth** [comment]
This was all about bundling, and bundling is gone.
