### ISSUE TITLE
Weird: after error, a script can end up running later

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#35]
Suppose you `System.load(S)` because you want to play a video. The script S says:

```
module "K" { ... }
module "M" { ... }
import "K" as K, "M" as M;
playVideo();
```

The execution order is [K, M, S]. Suppose K's body throws. We are left in a state where K and M are in the registry; M and S have never executed.

The next script that imports M will cause the body of S to execute. (Per dherman.) The video starts playing then. It seems weird for code that you wanted to run for its side effects to end up in the dependency graph like this.

**Comment by samth** [comment]
I think this must be a misunderstanding of what @dherman said. Importing M
should cause _M_ to execute, but not S.  That or dherman is crazy. :)

**Comment by samth** [comment]
No longer relevant in the absence of scripts.

**Comment by dherman** [comment]
Clarification: in particular, not relevant since scripts combined top-level executable code and module declarations. Without inline modules this goes away.
