### ISSUE TITLE
Consider moving module declaration (bundling) syntax to the browser loader

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#37]

**Comment by jorendorff** [comment]
Some arguments in favor:
- Bundling is logically a deployment issue, so it does not belong in the language proper, as long as other features can satisfy the use cases.
- Bundling via the fetch hook is semantically the same as loading the unbundled modules from files. For example, syntax errors and link errors in modules you _don't_ use will not cause loading to fail, and imports in modules you don’t use do not trigger additional loads. `module` is different.
- The fetch hook is sufficient for bundling.
- We can still provide a batteries-included fetch hook in the browser.
- This eliminates issues related to execution order of modules and their enclosing scripts. We have rules for this but they are weird and the implementation is weird. See [ensureExecuted in impl.js](https://people.mozilla.com/~jorendorff/js-loaders/impl.html), where it says “The `$SetRemove` call here means…”. That code will go away.
- The `module` syntax would throw if the module was already in the loader's registry or if a load was in-flight. For the purpose of deployment, it is better to silently discard anything in a bundle that you've already got. In particular this allows the server to send a bundle containing everything, without needing to know or care what the client already has. This is what fetch-hook-based bundling will do.
- This eliminates considerable complexity in the implementation. resolve().extra goes away. The “intrinsics” required from the implementation are simplified. $ScriptDeclaredModuleNames, $ScriptGetDeclaredModule, and $ModuleGetDeclaringScript go away. $ScriptImports can return an array of request strings rather than an array of [client, request] pairs.

**Comment by samth** [comment]
Arguments against:
- No longer possible to write modules at the REPL.
- No longer possible to write a modular program by just evolving something written in a single HTML page, because no modules in `<script>` tags.
- Can't use script tags as a deployment mechanism until the browser supports some new form or language.
- Lots of things are inconvenient unless/until we add lexical modules.

**Comment by jorendorff** [comment]
Another (meta-) argument against is that the proposed new bundling format doesn't exist yet. The proposal is not concrete enough on that point to be criticized. Obviously it should be an (a) already-defined format that supports (b) compression, (c) unicode, and (d) fast lookup of individual files, and (e) is just plain text, so humans can edit it. ;-)

**Comment by jorendorff** [comment]
I don't think we should worry about the repl though. The repl is for shortish scraps of code, all by one author, sort of the opposite of modules.

@samth, if you want to be more explicit about "lots of things", it'd help.

**Comment by samth** [comment]
@jorendorff I disagree about the REPL.  The repl is for playing around and trying things out; learning about new features is often easiest at the repl.  We want modules to be easy to try and easy to learn, which means that the repl is important.

On "lots of things": refactoring your single-file program to add modules, using modules in a script tag that's the whole program, writing a whole program in an emacs buffer or a Gist, hacking on the output of the concatenator.  Those are few examples, I could come up with others.

Finally, I thing the script tag issue is serious -- not being able to use script tags as a deployment mechanism is scary, I think.

**Comment by jorendorff** [comment]
Regarding the repl, I agree with 100% of this:

> The repl is for playing around and trying things out; learning about new features is often easiest at the repl. We want modules to be easy to try and easy to learn, which means that the repl is important.

But your conclusion doesn't follow! I learned all about python modules by doing exactly this sort of playing around in the python repl, even though there is no such thing as a module-declaration in python and no syntactic way to type a module into the python repl. There's no magic rule that says that when using a repl you have to forget files exist and communicate with the language solely via the prompt. To the contrary, when you're learning about a feature that is all about code organization across multiple files, you want your editor and the repl open at once. There is no point learning to do it one way in the repl and then having to unlearn some stuff and learn a different way when you go to use the feature for real.

**Comment by jorendorff** [comment]
Those "lots of things" use cases leave me a little cold. In practice, I transition from a single file to modules _because_ I want to change the code organization, i.e. a single file is no longer what I want.

The deployment thing is compelling. The rest, meh. Hacking on the output of a build tool, I dunno, I've done it... not something I'd want to put into a rationale document as a motivating scenario.

Gists support multiple files. Not sure about emacs _buffers_ as such.

**Comment by samth** [comment]
On the REPL, I think:
- it reduces the barrier to entry to not have to use files
- for JS, files are more complicated, and thus the REPL is _more_ important
- I've used languages that work both ways, and it's nice being able to try modules at the REPL.

More generally, in Racket multi-module files are hard to write and a special case, and we _added_ that special case to make things like testing and repls and examples and writing programs in email easier.

The "deploy-in-`<script>`" point is the only really killer issue, but I think there's a real cost to not supporting modules everywhere, even if you can get along without it.
