### ISSUE TITLE
Synchronous fetch function

### ISSUE THREAD

**Issue by guybedford** [jorendorff/js-loaders#38]
I wanted to point out one issue caused by delaying synchronous fetching.

There is the potential for plugins to allow other resources to be loaded - templates, and style (https://github.com/guybedford/require-css).

I know these are now the domain of the HTML Imports system, but I still like the benefits of having the same resource API for both.

Allowing a loader to have a synchronous fetch function allows a loader to load style synchronously, effectively doing the work of HTML imports.

For example:

``` html
  <script>
    customLoader.syncLoad('style!app/my-style');
  </script>
```

The synchronous behaviour is only in development, as builds would inline. The benefit here is that builds can cover both style and JavaScript etc.

I'm not saying this approach is a definite must, or even trying to say that it is even a good thing. But I do like the principle of having the same resolution API for all resources in a way that is build compatible as it does feel elegant. HTML Imports certainly have a place, but I just wanted to point out that this door is being closed by forcing the fetch function to be asynchronous as the flash of content with these approaches will make it a bad development experience.

**Comment by samth** [comment]
I'm confused about what you're suggesting.  First, the HTML imports system is declarative, and therefore doesn't block the main thread of execution, exactly in the same way as declarative `import` declarations in ES6 modules work. If there was a JS way to doing an HTML import (which I hope there is) then it would have to be async.  Second, are you suggesting that sync loading would only work for some modules, which are really styles?  How would that be checked?  Finally, you are suggesting a "development-only" mode.  How would we prevent people from using that in production?

In general, there's basically no chance that we (or anyone else) are going to add synchronous IO to JS or the browser environment.

**Comment by guybedford** [comment]
Ah, I wasn't aware that the HTML imports system had no blocking ability.

We must not forget that while it has caused performance problems, it is a useful feature that `<script>` and `<link>` tags for styles in the head block the rendering of the page. HTML should only be rendered once certain critical scripts and styles have been loaded, otherwise one gets flashes of content changes.

The fact that the HTML import system doesn't provide any blocking functionality is worrying, as how does an initial HTML page containing custom elements with scoped styles load then without those styles and scripts causing a flash of content and enhancement when finally loaded asynchronously?

This will force users to move away from writing HTML in the body and instead do all rendering themselves after the page load, which will directly affect Google's core business of indexing HTML. If it is possible not to do this, why avoid it?

Loading synchronously is only important while the document is being written. After this stage, all loads should be asynchronous, but it is these render-critical loads in particular that I am pointing out.

My example was badly illustrated... here is a better demonstration of the synchronous loading technique for scripts and styles using an ES6 loader polyfill:

http://jsbin.com/eforeq/2/edit

The difference between pre-optimized and optimized pages is that scripts are compiled and bundled. All blocking scripts would ideally be bundled into one or two tags in the head when optimized. So the performance loss of having deep imports and dependencies loaded synchronously is only one seen in development.

I'm not asking for this to be endorsed, or even clearly supported. I'm just pointing that it is possible with a synchronous fetch function, including support for style loading, and will not be possible anymore if the event loop is set to spin on fetch fulfillment. Quietly allow this, and loader creators who know what they are doing can take advantage of it, allowing ES6 loaders to entirely replace the need for `<script>` and `<link>` tags in the head in some cases. Disable the feature, and ES6 modules will never be able to provide this functionality for anyone.

**Comment by guybedford** [comment]
After some discussion on the public-webapps list it seems that HTML imports are in fact blocking of the page rendering.

I suppose the key distinction here is that I am referring to "blocking page rendering" not "blocking threads".

So the key point is how to implement an import that is render-critical.

An alternative to a synchronous fetch function in a custom loader, would simply be to ensure the following:

``` html
  <div id="my-slideshow">
  </div>
  <script>
    import $ from "jQuery";
    $('#my-slideshow').createSlideshow();
  </script>
  <h1>By the time this renders, the slideshow will be working</h1>
```

Behaves such that the `<h1>` is only rendered after the slideshow has been enhanced.

It's a little bit of a contrived example, but having scripts block rendering can be important.

Let me know also if I am having this discussion in completely the wrong place!

**Comment by dherman** [comment]
There's strong sentiment all around that we're sticking to a purely async API, so I'm closing this. @guybedford -- I'm not trying to shut down discussion, but I think at this point I can't see any way that synchronous loading would fly with TC39. And the idea of having elements depend on script seems like something that should maybe be solved at the HTML level rather than the ECMAScript level.

Dave

**Comment by guybedford** [comment]
Sure thanks for updating here, I've been assuming that was the case, and I don't think that's a problem at all - I just wanted to be clear to understand how modules can work with widgets.

I believe quite strongly that ES6 modules offer a better system for modular widgets than HTML imports, due to the more developed dependency management principles, so my consideration here was only how they can be used with render-critical HTML.

The solution then, given the above, is exactly as for webfonts - classes on the body to indicate the loading state of the page. Something like:

``` html
<script>
  System.import('jquery', function($) {
    $(document.body).removeClass('loading');
    $('.widget').widget();
  });
</script>
<body class="loading">
  <div class="widget"></div>
</body>
```
