### ISSUE TITLE
Realm_create has "this" reference which is undefined in strict mode.

### ISSUE THREAD

**Issue by briandipalma** [jorendorff/js-loaders#48]
I'm trying out the Loader code in FF nightly and I'm getting a "this" is undefined error in

function Realm_create() {
    //> 1.  Let F be the this value.
    //> 2.  Let realm be the result of calling
    //>     OrdinaryCreateFromConstructor(F, "%RealmPrototype%", ([[Realm]])).
    var realm = $ObjectCreate(this.prototype);

, this makes sense as the IIFE is strict mode.

**Comment by jorendorff** [comment]
Fixed now. But don't expect the code in this repo to work. It's untested and likely contains a lot of bugs.

**Comment by briandipalma** [comment]
Would you rather I not raise issues I find? I'm happy to raise issues if you don't mind but I won't if you deem it premature. I'm playing with this code to try and help me understand modules and the effect they will have on web/JS development.

**Comment by jorendorff** [comment]
Thanks for the bug report! I didn't mean to seem ungrateful, I just wanted to make it clear that the code just generally isn't going to run at this point.

**Comment by briandipalma** [comment]
No worries I didn't think you sounded ungrateful, I took what you said at face value, I was asking a serious question. I'll leave you guys to work away on the spec and code as it seems I'm jumping the gun :)

**Comment by jorendorff** [comment]
Thanks for the help. Right now, patches for obvious bugs are welcome :) but bug reports are probably premature.
