### ISSUE TITLE
how does resolve hook determine source type

### ISSUE THREAD

**Issue by dherman** [jorendorff/js-loaders#5]
The resolve hook is where we consult the @ondemand table and therefore is where we know whether the resulting address is a module or a script. But it is the fetch hook that is responsible for producing that information, passing it to the fulfill callback. Need to figure out how the information gets from here to there.

**Comment by dherman** [comment]
Partially resolved: The resolve hook may return a pair `{url: "blah", type: "script"}`, per @dherman, 2013 April 22.

That leaves two questions:
1. Is the type passed to the fetch hook, on the options object? (Current implementation assumes yes.)
2. Does the fulfill hook take a type parameter, so that the fetch hook can overrule what the resolve hook said? (Current implementation assumes yes.)

**Comment by samth** [comment]
1. Yes.
2. Yes (and this is in the google doc).

**Comment by jorendorff** [comment]
Yep. But it was worth confirming after we changed resolve. Thanks.

Is the rationale for (2) the done() callback? Or is there another reason to turn a module fetch into a script fetch?

The opposite, turning a script fetch into a module fetch, is not allowed. Right?

**Comment by jorendorff** [comment]
Oh, actually I guess we can support turning a script fetch into a module fetch if we're importing a module, just not if we're doing System.load().

Would still like to know if there's a reason for the type argument to fulfill() other than to support bulk-fetching.

**Comment by samth** [comment]
I think either direction should be allowed.

The reasons for the type argument are so that you can fetch things at once, but not necessarily bulk-fetching in the specific way that the `done()` callback is about.  For example, imagine that I import `"A"`, which will import `"B"`.  That could involve two http requests, but the server and client could collaborate to just ship a single script in the first request with both of them.

**Comment by jorendorff** [comment]
Hmm. That would be even easier to implement without changing the type, though. Make your custom resolve hook always say "script" and make your server always send a script.

**Comment by samth** [comment]
Yes, but that requires the decision to be made definitively on the client side.  Allowing a type argument to fulfill makes it possible for the server to make the decision as well if that works better.  I know YUI in some cases has servers making these choices.

**Comment by jorendorff** [comment]
But the server could decide, and in the case that it decides not to bundle, return a script containing the single module requested.

**Comment by jorendorff** [comment]
Resolved in the meeting: remove the type argument for now and require loaders to figure out what type to expect in the resolve hook.
