### ISSUE TITLE
Add an appropriate license

### ISSUE THREAD

**Issue by benjamn** [jorendorff/js-loaders#51]
Presumably the Mozilla Public License, but also something compatible with whatever licenses govern ECMA specifications?

**Comment by arv** [comment]
@dherman @samth @jorendorff Any progress on this? Would you accept a PR with MIT? ASL? MPL?

**Comment by samth** [comment]
Fixed by 99d5a8fa280c1d.

**Comment by jorendorff** [comment]
Incidentally, I only used MPL because it's super trivial to do and I think it's plenty permissive enough.

If an even more permissive license would help in any way, don't hesitate to ask.
