### ISSUE TITLE
Semantics of import ModuleSpecifier

### ISSUE THREAD

**Issue by arv** [jorendorff/js-loaders#61]
The ES wiki states that:

```
ImportDeclaration ::= "import" ImportSpecifierSet "from" ModuleSpecifier ";"      // explicit import declaration (fetch and execute dependency)
                   |  "import" ModuleSpecifier ";"                                // implicit import declaration (fetch dependency only)
```

Especially the "fetch only" part. How can I come to that conclusion based on the current spec draft?

The semantics of `import {} from 'name'` is to execute. How is this propagated through? I feel like there is some flag/argument that might not be passed through somewhere.

**Comment by zenparsing** [comment]
Why are we including a pre-fetching feature at the level of static linking semantics?  This is a clear violation of stratification.  What is the justification for this choice?

**Comment by jorendorff** [comment]
The wiki is wrong. `import "name";` is equivalent to `import {} from "name";` in the proposed spec.

**Comment by samth** [comment]
I've fixed the wiki.
