### ISSUE TITLE
1.1.1.7 ProceedToFetch [[AddressPromise]] is never used

### ISSUE THREAD

**Issue by arv** [jorendorff/js-loaders#62]
1. Set F.[[AddressPromise]] to p

Where F is  a CallFetch function. The CallFetch function does not have an internal slot called [[AddressPromise]]

**Comment by guybedford** [comment]
~~I included this in https://github.com/jorendorff/js-loaders/issues/58~~

**Comment by guybedford** [comment]
Are you sure you don't mean 1.1.1.7 ProceedToFetch here?

**Comment by arv** [comment]
@guybedford Corrected

**Comment by guybedford** [comment]
So to be clear, 1.1.1.7, step 4 can be omitted?

**Comment by guybedford** [comment]
@arv are we perhaps looking at different numberings? I'm looking at https://github.com/jorendorff/js-loaders/blob/master/specs/es6-modules-2013-12-02.pdf

**Comment by arv** [comment]
Correct. I copy pasted the wrong heading in the first place.

**Comment by guybedford** [comment]
Thanks - just don't want to be missing anything on this.
