### ISSUE TITLE
1.1.3 AsyncStartLoadPartwayThrough Functions 

### ISSUE THREAD

**Issue by arv** [jorendorff/js-loaders#66]
Each LoadSucceeded function has internal slots [[Loader]], [[ModuleName]], [[Step]], 
[[ModuleMetadata]], [[ModuleAddress]], and [[ModuleSource]]. 

Typo:

s/LoadSucceeded/AsyncStartLoadPartwayThrough/

**Comment by jorendorff** [comment]
Thanks.
