### ISSUE TITLE
default resolve behavior vs common-sense URL's

### ISSUE THREAD

**Issue by dherman** [jorendorff/js-loaders#7]
Again suppose we have loaded a module `"a/b/c"` from the url `"http://example.com/scripts/a/b/c.js"`, and it contains

``` js
import "x" as x;
```

The system loader's default resolve behavior produces the full name `"x"` and the url `"http://example.com/scripts/a/b/x.js"`. That can't be right.

**Comment by dherman** [comment]
The default _normalize_ behavior produces the full name `"x"`, and then the default _resolve_ behavior produces `baseURL + "x" + ".js"`, IOW, `"http://example.com/scripts/x.js"`.

Dave

**Comment by samth** [comment]
Note that to get the URL @jorendorff was thinking of you could do:

```
import "./x" as x;
```

**Comment by jorendorff** [comment]
Makes perfect sense.
