### ISSUE TITLE
Consider allowing module names below baseURL

### ISSUE THREAD

**Issue by guybedford** [jorendorff/js-loaders#76]
In the implementation, this can be included by treating a negative `stop` value in the `System.normalize` function as the initial number of `../` before the module name.

**Comment by amatiasq** [comment]
I think this is a basic feature, it's confusing if it's not allowed since CommonJS and AMD already allow it. A simple use case is a test html page inside a bigger project, where the page doesn't need to be at the root directory, it will need to load modules below baseURL. :+1:

**Comment by guybedford** [comment]
This does not make sense since module names are absolute references.
