### ISSUE TITLE
synchronous calls to fulfill()

### ISSUE THREAD

**Issue by samth** [jorendorff/js-loaders#9]
The agreed behavior above means that fetch() can
synchronously call fulfill(), which can synchronously call fetch().
Too confusing?  Maybe fulfill should stop after compilation and
handle imports/linking asynchronously.

**Comment by samth** [comment]
I think that sync calls to `fulfill()` should queue all the work to happen in the next turn.

**Comment by jorendorff** [comment]
Implemented.
