### ISSUE TITLE
'referrer' is misspelled

### ISSUE THREAD

**Issue by johnjbarton** [jorendorff/js-loaders#95]
The word in English is 'referrer':
http://www.thefreedictionary.com/Referrer
http://en.wiktionary.org/wiki/referrer

DOM decided to spell it the way English does:
https://developer.mozilla.org/en-US/docs/Web/API/document.referrer

HTTP decided to spell it the way some CS major did:
http://en.wikipedia.org/wiki/HTTP_referer

If we decide to use the misspelling (fine by me) then the spec should call it out explicitly.

**Comment by jorendorff** [comment]
Oh! I didn't know DOM had taken this bold stand in favor of correct spelling.

We should follow, I think. (This isn't even an API change, since we don't have anything named "referer" except parameters and spec fiction.)

**Comment by johnjbarton** [comment]
Another suggestion: change 'referrer' to 'importer'.  Referrer is rather loose, and 'importer' helps us concentrate on the relationship.

**Comment by briandipalma** [comment]
> Another suggestion: change 'referrer' to 'importer'. Referrer is rather loose, and 'importer' helps us concentrate on the relationship.

I like that suggestion, it does make it clearer.
