### ISSUE TITLE
Errors rather than internally converting argument: Loader.set()/get()/has()

### ISSUE THREAD

**Issue by johnjbarton** [jorendorff/js-loaders#98]
In 1.6.3.11 Loader.prototype.set ( name, module )

```
The following steps are taken: 
1. Let loader be this Loader. 
2. ReturnIfAbrupt(loader). 
3. Let name be ToString(name). 
```

IMO we should not be converting arguments. We should not allow non-string arguments; we should throw is the argument is not a string.  Having modules stored / retrieved under keys like "[object Window]" or "[object Object]" will lead to difficult to debug errors.  (I assume ToString() causes conversion, the doc does not say).

**Comment by arv** [comment]
That is just how JS behaves. We should follow suite for consistency.

**Comment by johnjbarton** [comment]
Sorry I don't follow your reasoning. What part of JS  prevents us from throwing an error if the argument is not a string?

**Comment by arv** [comment]
Almost all functions in ES5 and the DOM that expects a string accepts any
object and it will call toString on it as needed.

**Comment by jorendorff** [comment]
I'm with jjb in spirit but we're not inventing a language from scratch here. There is no way we are going to break with how every other JS API in the spec (and the universe at large) behaves.

**Comment by johnjbarton** [comment]
But you'll return iterators when other APIs return arrays?

**Comment by arv** [comment]
Other APIs return iterators. Map, Set and Array all return iterators.

**Comment by johnjbarton** [comment]
Well other new ES6 APIs return iterators. Given that inconsistency, then it makes sense for Loader to  follow.
