### ISSUE TITLE
Loader.keys() needs better name or definition.

### ISSUE THREAD

**Issue by johnjbarton** [jorendorff/js-loaders#99]
Since ES Object.keys() and many other ES function ending in 's' return arrays, devs deserve an array from Loader.keys().  If that is somehow impossible, then we need a better name for the function.  An obvious choice would be Loader.keyIterator().

**Comment by arv** [comment]
Loader implements the Map interface. If you want an array of the keys do:

``` js
[...map.keys()]
```

or

``` js
Array.from(map.keys())
```

**Comment by jorendorff** [comment]
Agreed.

**Comment by johnjbarton** [comment]
Loader implements the Map interface, but the API function 'keys()' is inconsistent with the rest of ES6 where keys() returns an array. This kind of inconsistency makes APIs harder to use.

**Comment by anba** [comment]
`Array|Map|Set.prototype.keys()` all return Iterator objects, not arrays.
